import type {
  Activity,
  Campaign,
  Conversation,
  Database,
  Lead,
  LeadAnalysis,
  LeadScoreEntry,
  Message,
  Note,
  PipelineStage,
  Proposal,
  Task,
  User,
} from "@/types";
import { computeScore } from "@/services/scoring";

/**
 * Seed de demonstração com dados realistas.
 * Todas as datas são relativas ao momento da geração.
 */

const ORG_ID = "org_atlas";

function iso(daysAgo: number, hour = 10, minute = 0): string {
  const d = new Date();
  d.setDate(d.getDate() - daysAgo);
  d.setHours(hour, minute, 0, 0);
  return d.toISOString();
}

function future(days: number, hour = 10): string {
  const d = new Date();
  d.setDate(d.getDate() + days);
  d.setHours(hour, 0, 0, 0);
  return d.toISOString();
}

export const STAGE_IDS = {
  novo: "stg_novo",
  analisado: "stg_analisado",
  qualificado: "stg_qualificado",
  pronto: "stg_pronto",
  contatado: "stg_contatado",
  respondeu: "stg_respondeu",
  interessado: "stg_interessado",
  demo: "stg_demo",
  reuniao: "stg_reuniao",
  proposta: "stg_proposta",
  negociacao: "stg_negociacao",
  fechado: "stg_fechado",
  perdido: "stg_perdido",
} as const;

const USERS: User[] = [
  {
    id: "usr_zack",
    organization_id: ORG_ID,
    name: "Zack Isaac",
    email: "zackisaacdev@gmail.com",
    role: "owner",
    avatar_url: null,
    created_at: iso(90),
  },
  {
    id: "usr_mariana",
    organization_id: ORG_ID,
    name: "Mariana Costa",
    email: "mariana@atlasdigital.com",
    role: "sdr",
    avatar_url: null,
    created_at: iso(60),
  },
  {
    id: "usr_rafael",
    organization_id: ORG_ID,
    name: "Rafael Almeida",
    email: "rafael@atlasdigital.com",
    role: "vendedor",
    avatar_url: null,
    created_at: iso(60),
  },
];

const STAGES: PipelineStage[] = [
  { id: STAGE_IDS.novo, organization_id: ORG_ID, name: "Novo", order: 0, color: "#94a3b8", is_won: false, is_lost: false },
  { id: STAGE_IDS.analisado, organization_id: ORG_ID, name: "Analisado", order: 1, color: "#818cf8", is_won: false, is_lost: false },
  { id: STAGE_IDS.qualificado, organization_id: ORG_ID, name: "Qualificado", order: 2, color: "#38bdf8", is_won: false, is_lost: false },
  { id: STAGE_IDS.pronto, organization_id: ORG_ID, name: "Pronto para contato", order: 3, color: "#2dd4bf", is_won: false, is_lost: false },
  { id: STAGE_IDS.contatado, organization_id: ORG_ID, name: "Contatado", order: 4, color: "#fbbf24", is_won: false, is_lost: false },
  { id: STAGE_IDS.respondeu, organization_id: ORG_ID, name: "Respondeu", order: 5, color: "#fb923c", is_won: false, is_lost: false },
  { id: STAGE_IDS.interessado, organization_id: ORG_ID, name: "Interessado", order: 6, color: "#f472b6", is_won: false, is_lost: false },
  { id: STAGE_IDS.demo, organization_id: ORG_ID, name: "Demo", order: 7, color: "#c084fc", is_won: false, is_lost: false },
  { id: STAGE_IDS.reuniao, organization_id: ORG_ID, name: "Reunião", order: 8, color: "#a78bfa", is_won: false, is_lost: false },
  { id: STAGE_IDS.proposta, organization_id: ORG_ID, name: "Proposta", order: 9, color: "#60a5fa", is_won: false, is_lost: false },
  { id: STAGE_IDS.negociacao, organization_id: ORG_ID, name: "Negociação", order: 10, color: "#34d399", is_won: false, is_lost: false },
  { id: STAGE_IDS.fechado, organization_id: ORG_ID, name: "Fechado", order: 11, color: "#0e9f6e", is_won: true, is_lost: false },
  { id: STAGE_IDS.perdido, organization_id: ORG_ID, name: "Perdido", order: 12, color: "#f87171", is_won: false, is_lost: true },
];

const CAMPAIGNS: Campaign[] = [
  {
    id: "cmp_imob_porto",
    organization_id: ORG_ID,
    name: "Imobiliárias Porto — Agosto",
    description: "Imobiliárias no Porto sem site próprio ou com site fraco.",
    created_at: iso(18),
    archived: false,
  },
  {
    id: "cmp_clinicas_sp",
    organization_id: ORG_ID,
    name: "Clínicas São Paulo — Julho",
    description: "Clínicas de estética e saúde na capital paulista.",
    created_at: iso(45),
    archived: false,
  },
];

type LeadSeed = Omit<
  Lead,
  "lead_score" | "temperature" | "organization_id" | "archived" | "updated_at"
> & { updated_at?: string };

function mkLead(seed: LeadSeed): Lead {
  const { score, classification } = computeScore(seed);
  return {
    ...seed,
    organization_id: ORG_ID,
    lead_score: score,
    temperature: classification,
    archived: false,
    updated_at: seed.updated_at ?? seed.created_at,
  };
}

const LEADS: Lead[] = [
  mkLead({
    id: "lead_gomes_freitas",
    company_name: "Gomes & Freitas Imóveis",
    contact_name: "Tiago Gomes",
    legal_name: "Gomes & Freitas Mediação Imobiliária Lda",
    segment: "Imobiliária",
    description: "Imobiliária com carteira ativa de imóveis para venda e arrendamento no Porto.",
    phone: "+351 22 208 4471",
    whatsapp: "+351 912 447 320",
    email: "geral@gomesfreitas.pt",
    website: null,
    instagram: "@gomesfreitasimoveis",
    facebook: "gomesfreitasimoveis",
    linkedin: null,
    google_maps_url: "https://maps.google.com/?q=Gomes+%26+Freitas+Im%C3%B3veis+Porto",
    country: "Portugal",
    state: "Porto",
    city: "Porto",
    address: "Rua de Santa Catarina, 812",
    reviews_count: 47,
    rating: 4.6,
    opening_hours: "Seg–Sex 9h–19h, Sáb 9h–13h",
    source: "demo",
    source_id: null,
    campaign_id: "cmp_imob_porto",
    has_website: false,
    website_quality: "nenhum",
    has_whatsapp: true,
    instagram_active: true,
    marketing_signals: true,
    business_active: true,
    catalog_size: "grande",
    status: "pronto_contato",
    pipeline_stage_id: STAGE_IDS.pronto,
    stage_entered_at: iso(2),
    potential_value: 3800,
    assigned_to: "usr_mariana",
    created_at: iso(6, 9, 12),
    last_contact_at: null,
    next_follow_up_at: null,
  }),
  mkLead({
    id: "lead_horizonte_prime",
    company_name: "Horizonte Prime Imóveis",
    contact_name: "Marta Figueiredo",
    legal_name: null,
    segment: "Imobiliária",
    description: "Imobiliária focada em apartamentos e moradias em Vila Nova de Gaia.",
    phone: "+351 22 375 9902",
    whatsapp: "+351 934 118 407",
    email: "contacto@horizonteprime.pt",
    website: "http://horizonteprime-imoveis.blogspot.com",
    instagram: "@horizonteprimeimoveis",
    facebook: null,
    linkedin: null,
    google_maps_url: "https://maps.google.com/?q=Horizonte+Prime+Im%C3%B3veis",
    country: "Portugal",
    state: "Porto",
    city: "Vila Nova de Gaia",
    address: "Avenida da República, 1244",
    reviews_count: 31,
    rating: 4.4,
    opening_hours: "Seg–Sex 9h–18h",
    source: "demo",
    source_id: null,
    campaign_id: "cmp_imob_porto",
    has_website: true,
    website_quality: "ruim",
    has_whatsapp: true,
    instagram_active: true,
    marketing_signals: false,
    business_active: true,
    catalog_size: "grande",
    status: "contatado",
    pipeline_stage_id: STAGE_IDS.contatado,
    stage_entered_at: iso(3),
    potential_value: 3200,
    assigned_to: "usr_mariana",
    created_at: iso(8, 14, 30),
    last_contact_at: iso(3, 11, 5),
    next_follow_up_at: future(-1, 10),
  }),
  mkLead({
    id: "lead_oliveira_motors",
    company_name: "Oliveira Motors",
    contact_name: "Ricardo Oliveira",
    legal_name: "Oliveira Motors Comércio de Veículos Ltda",
    segment: "Loja de veículos",
    description: "Loja de seminovos multimarcas com cerca de 60 veículos em estoque.",
    phone: "+55 11 3812-4470",
    whatsapp: "+55 11 98122-4470",
    email: null,
    website: null,
    instagram: "@oliveiramotorssp",
    facebook: "oliveiramotors",
    linkedin: null,
    google_maps_url: "https://maps.google.com/?q=Oliveira+Motors+S%C3%A3o+Paulo",
    country: "Brasil",
    state: "SP",
    city: "São Paulo",
    address: "Av. Marquês de São Vicente, 1830 — Barra Funda",
    reviews_count: 128,
    rating: 4.3,
    opening_hours: "Seg–Sáb 9h–19h",
    source: "demo",
    source_id: null,
    campaign_id: null,
    has_website: false,
    website_quality: "nenhum",
    has_whatsapp: true,
    instagram_active: true,
    marketing_signals: true,
    business_active: true,
    catalog_size: "grande",
    status: "respondeu",
    pipeline_stage_id: STAGE_IDS.respondeu,
    stage_entered_at: iso(1),
    potential_value: 5200,
    assigned_to: "usr_rafael",
    created_at: iso(12, 10, 45),
    last_contact_at: iso(1, 15, 22),
    next_follow_up_at: future(0, 15),
  }),
  mkLead({
    id: "lead_clinica_lumina",
    company_name: "Clínica Lumina",
    contact_name: "Dra. Paula Sanches",
    legal_name: "Lumina Serviços Médicos Ltda",
    segment: "Clínica",
    description: "Clínica de dermatologia e estética com duas unidades em São Paulo.",
    phone: "+55 11 3097-5518",
    whatsapp: "+55 11 97430-5518",
    email: "contato@clinicalumina.com.br",
    website: "https://clinicalumina.com.br",
    instagram: "@clinicalumina",
    facebook: "clinicalumina",
    linkedin: "clinica-lumina",
    google_maps_url: "https://maps.google.com/?q=Cl%C3%ADnica+Lumina",
    country: "Brasil",
    state: "SP",
    city: "São Paulo",
    address: "Rua Oscar Freire, 379 — Jardins",
    reviews_count: 214,
    rating: 4.8,
    opening_hours: "Seg–Sex 8h–20h, Sáb 8h–14h",
    source: "demo",
    source_id: null,
    campaign_id: "cmp_clinicas_sp",
    has_website: true,
    website_quality: "desatualizado",
    has_whatsapp: true,
    instagram_active: true,
    marketing_signals: true,
    business_active: true,
    catalog_size: "medio",
    status: "interessado",
    pipeline_stage_id: STAGE_IDS.interessado,
    stage_entered_at: iso(2),
    potential_value: 6800,
    assigned_to: "usr_rafael",
    created_at: iso(20, 9, 0),
    last_contact_at: iso(2, 16, 40),
    next_follow_up_at: future(1, 14),
  }),
  mkLead({
    id: "lead_studio_norte",
    company_name: "Studio Norte Arquitetura",
    contact_name: "Camila Nogueira",
    legal_name: null,
    segment: "Arquiteto",
    description: "Escritório de arquitetura com projetos residenciais de alto padrão.",
    phone: "+55 41 3352-8890",
    whatsapp: "+55 41 99852-8890",
    email: "oi@studionorte.arq.br",
    website: null,
    instagram: "@studionorte.arq",
    facebook: null,
    linkedin: "studio-norte-arquitetura",
    google_maps_url: null,
    country: "Brasil",
    state: "PR",
    city: "Curitiba",
    address: "Rua Padre Anchieta, 2050 — Bigorrilho",
    reviews_count: 22,
    rating: 5.0,
    opening_hours: "Seg–Sex 9h–18h",
    source: "demo",
    source_id: null,
    campaign_id: null,
    has_website: false,
    website_quality: "nenhum",
    has_whatsapp: true,
    instagram_active: true,
    marketing_signals: false,
    business_active: true,
    catalog_size: "medio",
    status: "reuniao",
    pipeline_stage_id: STAGE_IDS.reuniao,
    stage_entered_at: iso(1),
    potential_value: 4500,
    assigned_to: "usr_zack",
    created_at: iso(25, 11, 20),
    last_contact_at: iso(1, 10, 0),
    next_follow_up_at: future(0, 16),
  }),
  mkLead({
    id: "lead_atlantico_imoveis",
    company_name: "Atlântico Imóveis",
    contact_name: "Rui Malheiro",
    legal_name: null,
    segment: "Imobiliária",
    description: "Mediação imobiliária em Matosinhos e zona costeira do Porto.",
    phone: "+351 22 938 1174",
    whatsapp: null,
    email: "atlantico.imoveis@sapo.pt",
    website: null,
    instagram: "@atlantico_imoveis",
    facebook: "atlanticoimoveis",
    linkedin: null,
    google_maps_url: "https://maps.google.com/?q=Atl%C3%A2ntico+Im%C3%B3veis+Matosinhos",
    country: "Portugal",
    state: "Porto",
    city: "Matosinhos",
    address: "Rua Brito Capelo, 97",
    reviews_count: 12,
    rating: 4.1,
    opening_hours: "Seg–Sex 9h30–18h30",
    source: "demo",
    source_id: null,
    campaign_id: "cmp_imob_porto",
    has_website: false,
    website_quality: "nenhum",
    has_whatsapp: false,
    instagram_active: false,
    marketing_signals: false,
    business_active: true,
    catalog_size: "medio",
    status: "analisado",
    pipeline_stage_id: STAGE_IDS.analisado,
    stage_entered_at: iso(4),
    potential_value: null,
    assigned_to: null,
    created_at: iso(5, 15, 10),
    last_contact_at: null,
    next_follow_up_at: null,
  }),
  mkLead({
    id: "lead_essenza_estetica",
    company_name: "Espaço Essenza Estética",
    contact_name: "Fernanda Lacerda",
    legal_name: null,
    segment: "Estética",
    description: "Centro de estética facial e corporal na Zona Oeste de São Paulo.",
    phone: "+55 11 2367-9012",
    whatsapp: "+55 11 96877-9012",
    email: null,
    website: null,
    instagram: "@espacoessenza",
    facebook: null,
    linkedin: null,
    google_maps_url: "https://maps.google.com/?q=Espa%C3%A7o+Essenza",
    country: "Brasil",
    state: "SP",
    city: "São Paulo",
    address: "Rua Clélia, 1104 — Perdizes",
    reviews_count: 89,
    rating: 4.7,
    opening_hours: "Seg–Sáb 9h–20h",
    source: "demo",
    source_id: null,
    campaign_id: "cmp_clinicas_sp",
    has_website: false,
    website_quality: "nenhum",
    has_whatsapp: true,
    instagram_active: true,
    marketing_signals: true,
    business_active: true,
    catalog_size: "medio",
    status: "proposta",
    pipeline_stage_id: STAGE_IDS.proposta,
    stage_entered_at: iso(5),
    potential_value: 2900,
    assigned_to: "usr_rafael",
    created_at: iso(38, 10, 0),
    last_contact_at: iso(5, 14, 15),
    next_follow_up_at: future(-2, 11),
  }),
  mkLead({
    id: "lead_rota_sul_motors",
    company_name: "Rota Sul Motors",
    contact_name: "AndersonLeal",
    legal_name: "Rota Sul Comércio de Veículos Ltda",
    segment: "Loja de veículos",
    description: "Revenda de veículos seminovos em Porto Alegre.",
    phone: "+55 51 3232-6641",
    whatsapp: "+55 51 99641-6641",
    email: "vendas@rotasulmotors.com.br",
    website: "https://rotasulmotors.com.br",
    instagram: "@rotasulmotors",
    facebook: "rotasulmotors",
    linkedin: null,
    google_maps_url: "https://maps.google.com/?q=Rota+Sul+Motors",
    country: "Brasil",
    state: "RS",
    city: "Porto Alegre",
    address: "Av. Assis Brasil, 4520 — Sarandi",
    reviews_count: 203,
    rating: 4.5,
    opening_hours: "Seg–Sáb 9h–19h",
    source: "demo",
    source_id: null,
    campaign_id: null,
    has_website: true,
    website_quality: "bom",
    has_whatsapp: true,
    instagram_active: true,
    marketing_signals: true,
    business_active: true,
    catalog_size: "grande",
    status: "novo",
    pipeline_stage_id: STAGE_IDS.novo,
    stage_entered_at: iso(1),
    potential_value: null,
    assigned_to: null,
    created_at: iso(1, 8, 40),
    last_contact_at: null,
    next_follow_up_at: null,
  }),
  mkLead({
    id: "lead_pousada_gaivotas",
    company_name: "Pousada das Gaivotas",
    contact_name: "Sérgio Anjos",
    legal_name: null,
    segment: "Pousada",
    description: "Pousada à beira-mar em Florianópolis com 14 quartos.",
    phone: "+55 48 3269-7753",
    whatsapp: "+55 48 99169-7753",
    email: "reservas@pousadadasgaivotas.com.br",
    website: null,
    instagram: "@pousadadasgaivotas",
    facebook: "pousadadasgaivotas",
    linkedin: null,
    google_maps_url: "https://maps.google.com/?q=Pousada+das+Gaivotas+Florian%C3%B3polis",
    country: "Brasil",
    state: "SC",
    city: "Florianópolis",
    address: "Rua das Gaivotas, 118 — Ingleses",
    reviews_count: 342,
    rating: 4.6,
    opening_hours: "Recepção 24h",
    source: "demo",
    source_id: null,
    campaign_id: null,
    has_website: false,
    website_quality: "nenhum",
    has_whatsapp: true,
    instagram_active: true,
    marketing_signals: false,
    business_active: true,
    catalog_size: "pequeno",
    status: "qualificado",
    pipeline_stage_id: STAGE_IDS.qualificado,
    stage_entered_at: iso(2),
    potential_value: 3400,
    assigned_to: "usr_mariana",
    created_at: iso(3, 13, 25),
    last_contact_at: null,
    next_follow_up_at: null,
  }),
  mkLead({
    id: "lead_vasconcelos_adv",
    company_name: "Vasconcelos Advogados",
    contact_name: "Dr. Hugo Vasconcelos",
    legal_name: "Vasconcelos Sociedade de Advogados",
    segment: "Advogado",
    description: "Escritório de advocacia empresarial em Lisboa.",
    phone: "+351 21 342 8860",
    whatsapp: null,
    email: "geral@vasconcelosadv.pt",
    website: "https://vasconcelosadv.pt",
    instagram: null,
    facebook: null,
    linkedin: "vasconcelos-advogados",
    google_maps_url: null,
    country: "Portugal",
    state: "Lisboa",
    city: "Lisboa",
    address: "Avenida da Liberdade, 110",
    reviews_count: 8,
    rating: 4.9,
    opening_hours: "Seg–Sex 9h–18h",
    source: "demo",
    source_id: null,
    campaign_id: null,
    has_website: true,
    website_quality: "bom",
    has_whatsapp: false,
    instagram_active: false,
    marketing_signals: false,
    business_active: true,
    catalog_size: "nenhum",
    status: "perdido",
    pipeline_stage_id: STAGE_IDS.perdido,
    stage_entered_at: iso(10),
    potential_value: 2000,
    assigned_to: "usr_rafael",
    created_at: iso(40, 9, 30),
    last_contact_at: iso(12, 10, 0),
    next_follow_up_at: null,
  }),
  mkLead({
    id: "lead_tempero_casa",
    company_name: "Restaurante Tempero da Casa",
    contact_name: "Dona Cida",
    legal_name: null,
    segment: "Restaurante",
    description: "Restaurante de comida caseira com delivery próprio no centro de Campinas.",
    phone: "+55 19 3234-5561",
    whatsapp: "+55 19 99734-5561",
    email: null,
    website: null,
    instagram: "@temperodacasacps",
    facebook: "temperodacasa",
    linkedin: null,
    google_maps_url: "https://maps.google.com/?q=Tempero+da+Casa+Campinas",
    country: "Brasil",
    state: "SP",
    city: "Campinas",
    address: "Rua Barão de Jaguara, 890 — Centro",
    reviews_count: 517,
    rating: 4.4,
    opening_hours: "Todos os dias 11h–15h, 18h–22h",
    source: "demo",
    source_id: null,
    campaign_id: null,
    has_website: false,
    website_quality: "nenhum",
    has_whatsapp: true,
    instagram_active: true,
    marketing_signals: false,
    business_active: true,
    catalog_size: "pequeno",
    status: "novo",
    pipeline_stage_id: STAGE_IDS.novo,
    stage_entered_at: iso(0),
    potential_value: null,
    assigned_to: null,
    created_at: iso(0, 8, 15),
    last_contact_at: null,
    next_follow_up_at: null,
  }),
  mkLead({
    id: "lead_urbana_moda",
    company_name: "Urbana Moda Store",
    contact_name: "Bianca Ramos",
    legal_name: null,
    segment: "Loja de roupas",
    description: "Loja de moda feminina com forte presença no Instagram e vendas via WhatsApp.",
    phone: "+55 31 3287-4433",
    whatsapp: "+55 31 98487-4433",
    email: "urbanamodastore@gmail.com",
    website: null,
    instagram: "@urbanamodastore",
    facebook: "urbanamodastore",
    linkedin: null,
    google_maps_url: "https://maps.google.com/?q=Urbana+Moda+Store+BH",
    country: "Brasil",
    state: "MG",
    city: "Belo Horizonte",
    address: "Rua da Bahia, 1148 — Centro",
    reviews_count: 64,
    rating: 4.7,
    opening_hours: "Seg–Sáb 10h–20h",
    source: "demo",
    source_id: null,
    campaign_id: null,
    has_website: false,
    website_quality: "nenhum",
    has_whatsapp: true,
    instagram_active: true,
    marketing_signals: true,
    business_active: true,
    catalog_size: "grande",
    status: "negociacao",
    pipeline_stage_id: STAGE_IDS.negociacao,
    stage_entered_at: iso(3),
    potential_value: 4100,
    assigned_to: "usr_zack",
    created_at: iso(30, 14, 0),
    last_contact_at: iso(3, 17, 30),
    next_follow_up_at: future(2, 10),
  }),
  mkLead({
    id: "lead_hotel_miradouro",
    company_name: "Hotel Miradouro",
    contact_name: "Isabel Quintas",
    legal_name: "Miradouro Hotelaria SA",
    segment: "Hotel",
    description: "Hotel de 3 estrelas com 42 quartos no centro histórico de Braga.",
    phone: "+351 25 326 7180",
    whatsapp: "+351 925 667 180",
    email: "reservas@hotelmiradouro.pt",
    website: "http://www.hotelmiradouro.pt",
    instagram: "@hotelmiradouro",
    facebook: "hotelmiradouro",
    linkedin: null,
    google_maps_url: "https://maps.google.com/?q=Hotel+Miradouro+Braga",
    country: "Portugal",
    state: "Braga",
    city: "Braga",
    address: "Largo do Paço, 22",
    reviews_count: 486,
    rating: 4.2,
    opening_hours: "Recepção 24h",
    source: "demo",
    source_id: null,
    campaign_id: null,
    has_website: true,
    website_quality: "desatualizado",
    has_whatsapp: true,
    instagram_active: false,
    marketing_signals: false,
    business_active: true,
    catalog_size: "medio",
    status: "fechado",
    pipeline_stage_id: STAGE_IDS.fechado,
    stage_entered_at: iso(7),
    potential_value: 5900,
    assigned_to: "usr_zack",
    created_at: iso(55, 10, 10),
    last_contact_at: iso(7, 15, 0),
    next_follow_up_at: null,
  }),
  mkLead({
    id: "lead_marina_nutri",
    company_name: "Marina Queirós Nutrição",
    contact_name: "Marina Queirós",
    legal_name: null,
    segment: "Nutricionista",
    description: "Nutricionista clínica e esportiva com atendimento presencial e online.",
    phone: null,
    whatsapp: "+55 21 96588-2214",
    email: "marina@queirosnutricao.com.br",
    website: null,
    instagram: "@marinaqueiros.nutri",
    facebook: null,
    linkedin: null,
    google_maps_url: null,
    country: "Brasil",
    state: "RJ",
    city: "Rio de Janeiro",
    address: "Av. das Américas, 3500 — Barra da Tijuca",
    reviews_count: 41,
    rating: 4.9,
    opening_hours: "Seg–Sex 8h–19h",
    source: "demo",
    source_id: null,
    campaign_id: null,
    has_website: false,
    website_quality: "nenhum",
    has_whatsapp: true,
    instagram_active: true,
    marketing_signals: false,
    business_active: true,
    catalog_size: "nenhum",
    status: "contatado",
    pipeline_stage_id: STAGE_IDS.contatado,
    stage_entered_at: iso(6),
    potential_value: 1800,
    assigned_to: "usr_mariana",
    created_at: iso(15, 16, 45),
    last_contact_at: iso(6, 9, 30),
    next_follow_up_at: future(-3, 9),
  }),
  mkLead({
    id: "lead_valeverde_imoveis",
    company_name: "Vale Verde Imóveis",
    contact_name: "Joaquim Ferraz",
    legal_name: null,
    segment: "Imobiliária",
    description: "Imobiliária de bairro com foco em locação residencial.",
    phone: "+351 22 617 3345",
    whatsapp: "+351 917 233 451",
    email: null,
    website: null,
    instagram: null,
    facebook: "valeverdeimoveis",
    linkedin: null,
    google_maps_url: "https://maps.google.com/?q=Vale+Verde+Im%C3%B3veis",
    country: "Portugal",
    state: "Porto",
    city: "Maia",
    address: "Rua Augusto Simões, 204",
    reviews_count: 6,
    rating: 3.9,
    opening_hours: "Seg–Sex 9h–18h",
    source: "demo",
    source_id: null,
    campaign_id: "cmp_imob_porto",
    has_website: false,
    website_quality: "nenhum",
    has_whatsapp: true,
    instagram_active: false,
    marketing_signals: false,
    business_active: true,
    catalog_size: "pequeno",
    status: "novo",
    pipeline_stage_id: STAGE_IDS.novo,
    stage_entered_at: iso(2),
    potential_value: null,
    assigned_to: null,
    created_at: iso(2, 11, 55),
    last_contact_at: null,
    next_follow_up_at: null,
  }),
  mkLead({
    id: "lead_braseiro_grill",
    company_name: "Braseiro Grill",
    contact_name: "Marcos Vinícius",
    legal_name: null,
    segment: "Restaurante",
    description: "Churrascaria com rodízio e eventos corporativos em Goiânia.",
    phone: "+55 62 3225-8890",
    whatsapp: "+55 62 99825-8890",
    email: "contato@braseirogrill.com.br",
    website: "https://braseirogrill.com.br",
    instagram: "@braseirogrill",
    facebook: "braseirogrill",
    linkedin: null,
    google_maps_url: "https://maps.google.com/?q=Braseiro+Grill+Goi%C3%A2nia",
    country: "Brasil",
    state: "GO",
    city: "Goiânia",
    address: "Av. T-4, 1478 — Setor Bueno",
    reviews_count: 892,
    rating: 4.5,
    opening_hours: "Todos os dias 11h30–23h",
    source: "demo",
    source_id: null,
    campaign_id: null,
    has_website: true,
    website_quality: "bom",
    has_whatsapp: true,
    instagram_active: true,
    marketing_signals: true,
    business_active: true,
    catalog_size: "pequeno",
    status: "analisado",
    pipeline_stage_id: STAGE_IDS.analisado,
    stage_entered_at: iso(4),
    potential_value: null,
    assigned_to: null,
    created_at: iso(4, 10, 20),
    last_contact_at: null,
    next_follow_up_at: null,
  }),
];

const ANALYSES: LeadAnalysis[] = [
  {
    id: "ana_gomes",
    lead_id: "lead_gomes_freitas",
    digital_presence_summary:
      "Instagram ativo com publicações quase diárias de imóveis (fotos e reels), 47 avaliações no Google com nota 4,6 e página no Facebook atualizada. Não existe site próprio: o link da bio aponta direto para o WhatsApp.",
    strengths: [
      "Instagram ativo com boa frequência de publicação",
      "Carteira grande de imóveis anunciados",
      "Boa reputação no Google (4,6 com 47 avaliações)",
    ],
    main_problem:
      "A empresa publica dezenas de imóveis pelo Instagram, porém não possui uma página própria onde o comprador consiga filtrar os imóveis por localização, tipologia ou faixa de preço. Quem chega pelo perfil precisa rolar o feed ou perguntar pelo WhatsApp o que está disponível.",
    problem_impact:
      "Isso aumenta a dependência do atendimento manual e pode fazer potenciais compradores desistirem antes de perguntar quais imóveis estão disponíveis no perfil que procuram.",
    recommended_solution: "Site imobiliário com listagem e filtros de imóveis",
    commercial_angle:
      "Facilitar a jornada de quem já chega pelo Instagram sem mudar a operação atual da imobiliária.",
    confidence: 92,
    model: "engine/deterministic-v1",
    created_at: iso(5, 16, 20),
  },
  {
    id: "ana_horizonte",
    lead_id: "lead_horizonte_prime",
    digital_presence_summary:
      "Instagram ativo com anúncios de imóveis e um site em plataforma de blog gratuita, sem domínio próprio, com listagem desorganizada e sem filtros. As fotos carregam lentamente e o site não funciona bem no celular.",
    strengths: [
      "Instagram ativo com anúncios frequentes",
      "Boa carteira de imóveis em Gaia",
    ],
    main_problem:
      "O site atual está hospedado em uma plataforma de blog gratuita, sem domínio próprio, não se adapta ao celular e não permite filtrar imóveis por tipologia ou preço — quem acessa precisa rolar uma lista única e desatualizada.",
    problem_impact:
      "Compradores que chegam pelo Google ou pela bio do Instagram encontram uma experiência que transmite pouca confiança e dificulta encontrar o imóvel certo, empurrando tudo para o atendimento manual.",
    recommended_solution: "Site imobiliário profissional com domínio próprio e filtros",
    commercial_angle:
      "Substituir o blog por uma vitrine própria que valorize a carteira de imóveis já existente.",
    confidence: 88,
    model: "engine/deterministic-v1",
    created_at: iso(7, 11, 10),
  },
  {
    id: "ana_oliveira",
    lead_id: "lead_oliveira_motors",
    digital_presence_summary:
      "Instagram muito ativo (posts diários de veículos, stories com novidades do pátio) e 128 avaliações no Google. Todo o processo de venda é direcionado para o WhatsApp. Não há site nem vitrine online do estoque.",
    strengths: [
      "Instagram ativo com estoque publicado diariamente",
      "Volume alto de avaliações no Google (128, nota 4,3)",
      "Sinais de investimento em marketing (posts patrocinados)",
    ],
    main_problem:
      "A loja publica os veículos individualmente no feed e direciona praticamente todo o processo para o WhatsApp. O comprador não possui uma vitrine onde consiga visualizar o estoque completo e filtrar por marca, modelo, ano e faixa de preço.",
    problem_impact:
      "Cada interessado precisa perguntar o que existe em estoque, o que multiplica o atendimento manual e faz a loja perder compradores que preferem pesquisar sozinhos antes de conversar.",
    recommended_solution: "Vitrine digital de estoque com filtros e integração com WhatsApp",
    commercial_angle:
      "Transformar o estoque que já é fotografado todos os dias em uma vitrine navegável, mantendo o fechamento pelo WhatsApp.",
    confidence: 94,
    model: "engine/deterministic-v1",
    created_at: iso(11, 9, 45),
  },
  {
    id: "ana_lumina",
    lead_id: "lead_clinica_lumina",
    digital_presence_summary:
      "Presença digital forte: Instagram com mais de 20 mil seguidores, 214 avaliações no Google (4,8) e site institucional. Porém o site não é atualizado desde 2022, não lista os procedimentos atuais e o agendamento é feito apenas por telefone.",
    strengths: [
      "Excelente reputação (4,8 com 214 avaliações)",
      "Instagram forte e ativo",
      "Duas unidades e equipe estruturada",
    ],
    main_problem:
      "O site institucional está desatualizado desde 2022: não apresenta os procedimentos que a clínica mais divulga no Instagram e não oferece nenhuma forma de agendamento online — o paciente precisa ligar em horário comercial para marcar consulta.",
    problem_impact:
      "Pacientes que pesquisam fora do horário comercial não conseguem agendar e parte deles segue para clínicas que oferecem agendamento imediato.",
    recommended_solution: "Site atualizado com agendamento online integrado",
    commercial_angle:
      "Alinhar o site à qualidade que a clínica já demonstra no Instagram e destravar agendamentos fora do horário comercial.",
    confidence: 90,
    model: "engine/deterministic-v1",
    created_at: iso(18, 14, 0),
  },
  {
    id: "ana_studio_norte",
    lead_id: "lead_studio_norte",
    digital_presence_summary:
      "Instagram com portfólio visual bem produzido e LinkedIn ativo. Não existe site: quem quer ver projetos completos, depoimentos ou entrar em contato precisa navegar pelos destaques do perfil.",
    strengths: [
      "Portfólio visual de alta qualidade no Instagram",
      "Nota máxima no Google (5,0)",
    ],
    main_problem:
      "O perfil apresenta os projetos do escritório, porém não existe uma estrutura própria que reúna portfólio completo, depoimentos de clientes e formulário de contato. Quem chega pelo Instagram precisa buscar essas informações manualmente pelos destaques.",
    problem_impact:
      "Clientes de alto padrão que pesquisam o escritório antes de contratar não encontram um espaço que consolide autoridade, e parte da primeira impressão fica dependente do algoritmo do Instagram.",
    recommended_solution: "Site portfólio com estudos de caso e formulário de contato",
    commercial_angle:
      "Consolidar em um endereço próprio a autoridade que o escritório já construiu no Instagram.",
    confidence: 87,
    model: "engine/deterministic-v1",
    created_at: iso(24, 10, 30),
  },
  {
    id: "ana_essenza",
    lead_id: "lead_essenza_estetica",
    digital_presence_summary:
      "Instagram ativo com antes/depois e stories diários, 89 avaliações no Google (4,7). Agendamentos exclusivamente pelo WhatsApp, sem página de serviços ou tabela de procedimentos.",
    strengths: [
      "Instagram ativo com conteúdo de resultados",
      "Boa reputação no Google",
    ],
    main_problem:
      "Todos os agendamentos dependem de conversa manual no WhatsApp: não existe uma página onde a cliente consiga ver a lista de procedimentos, valores a partir de, e escolher horário disponível.",
    problem_impact:
      "A recepção gasta horas por dia respondendo as mesmas perguntas sobre procedimentos e horários, e clientes que escrevem fora do horário comercial ficam sem resposta imediata.",
    recommended_solution: "Landing page de procedimentos com agendamento online",
    commercial_angle:
      "Reduzir o vai-e-vem no WhatsApp transformando as perguntas repetidas em uma página que responde sozinha.",
    confidence: 89,
    model: "engine/deterministic-v1",
    created_at: iso(36, 15, 40),
  },
  {
    id: "ana_urbana",
    lead_id: "lead_urbana_moda",
    digital_presence_summary:
      "Instagram forte (posts diários, alto engajamento) e vendas fechadas via WhatsApp e direct. Não há catálogo online nem e-commerce; o estoque muda semanalmente e é anunciado apenas nos stories.",
    strengths: [
      "Audiência engajada no Instagram",
      "Estoque grande com renovação semanal",
      "Investimento ativo em tráfego pago",
    ],
    main_problem:
      "As peças são vendidas apenas por stories e direct: não existe um catálogo navegável onde a cliente veja tamanhos disponíveis e preços sem precisar perguntar. Peças esgotadas continuam recebendo perguntas dias depois do story expirar.",
    problem_impact:
      "A equipe responde dezenas de mensagens repetidas por dia sobre preço e tamanho, e vendas se perdem quando a resposta demora mais do que o impulso de compra da cliente.",
    recommended_solution: "Catálogo online integrado ao WhatsApp",
    commercial_angle:
      "Transformar o fluxo de perguntas repetidas em um catálogo que vende enquanto a equipe atende quem já decidiu comprar.",
    confidence: 91,
    model: "engine/deterministic-v1",
    created_at: iso(28, 12, 0),
  },
  {
    id: "ana_pousada",
    lead_id: "lead_pousada_gaivotas",
    digital_presence_summary:
      "Presença relevante em OTAs (342 avaliações no Google) e Instagram ativo com fotos da praia. Reservas diretas apenas por telefone e WhatsApp; sem site próprio ou motor de reservas.",
    strengths: [
      "Ótima reputação com 342 avaliações",
      "Localização à beira-mar como diferencial claro",
    ],
    main_problem:
      "A pousada depende de portais de reserva que cobram comissão por cada hóspede: não existe um canal próprio onde o viajante veja fotos dos quartos, disponibilidade e faça a reserva direta.",
    problem_impact:
      "Parte da margem de cada reserva é entregue às plataformas, e hóspedes que gostariam de reservar direto acabam fechando pelos portais por falta de alternativa clara.",
    recommended_solution: "Site com motor de reservas diretas",
    commercial_angle:
      "Converter a reputação já conquistada nas plataformas em reservas diretas sem comissão.",
    confidence: 86,
    model: "engine/deterministic-v1",
    created_at: iso(2, 17, 10),
  },
];

const SCORE_HISTORY: LeadScoreEntry[] = LEADS.filter((l) => l.lead_score !== null).map((l) => ({
  id: `sch_${l.id}`,
  lead_id: l.id,
  score: l.lead_score!,
  classification: l.temperature!,
  factors: computeScore(l).factors,
  created_at: l.created_at,
}));

const ACTIVITIES: Activity[] = [
  { id: "act_01", organization_id: ORG_ID, lead_id: "lead_gomes_freitas", type: "lead_criado", description: "Lead encontrado via prospecção (campanha Imobiliárias Porto — Agosto)", user_id: "usr_mariana", created_at: iso(6, 9, 12) },
  { id: "act_02", organization_id: ORG_ID, lead_id: "lead_gomes_freitas", type: "lead_analisado", description: "Análise de oportunidade concluída — problema identificado: ausência de vitrine própria de imóveis", user_id: null, created_at: iso(5, 16, 20) },
  { id: "act_03", organization_id: ORG_ID, lead_id: "lead_gomes_freitas", type: "score_atualizado", description: "Score calculado: 95 (Quente)", user_id: null, created_at: iso(5, 16, 21) },
  { id: "act_04", organization_id: ORG_ID, lead_id: "lead_oliveira_motors", type: "primeiro_contato", description: "Primeira abordagem enviada por WhatsApp", user_id: "usr_rafael", created_at: iso(4, 10, 5) },
  { id: "act_05", organization_id: ORG_ID, lead_id: "lead_oliveira_motors", type: "resposta_recebida", description: "Lead respondeu: \"Como funcionaria isso?\"", user_id: null, created_at: iso(1, 15, 22) },
  { id: "act_06", organization_id: ORG_ID, lead_id: "lead_clinica_lumina", type: "reuniao", description: "Reunião de descoberta realizada por vídeo", user_id: "usr_rafael", created_at: iso(4, 15, 0) },
  { id: "act_07", organization_id: ORG_ID, lead_id: "lead_essenza_estetica", type: "proposta_enviada", description: "Proposta de landing page + agendamento enviada (R$ 2.900)", user_id: "usr_rafael", created_at: iso(5, 14, 15) },
  { id: "act_08", organization_id: ORG_ID, lead_id: "lead_hotel_miradouro", type: "fechamento", description: "Negócio fechado — site com motor de reservas (R$ 5.900)", user_id: "usr_zack", created_at: iso(7, 15, 0) },
  { id: "act_09", organization_id: ORG_ID, lead_id: "lead_vasconcelos_adv", type: "perda", description: "Lead perdido — já possui fornecedor de confiança", user_id: "usr_rafael", created_at: iso(10, 11, 30) },
  { id: "act_10", organization_id: ORG_ID, lead_id: "lead_urbana_moda", type: "etapa_alterada", description: "Movido para Negociação", user_id: "usr_zack", created_at: iso(3, 17, 30) },
  { id: "act_11", organization_id: ORG_ID, lead_id: "lead_studio_norte", type: "reuniao", description: "Reunião marcada para apresentação de proposta", user_id: "usr_zack", created_at: iso(1, 10, 0) },
];

const NOTES: Note[] = [
  {
    id: "note_01",
    lead_id: "lead_clinica_lumina",
    author_id: "usr_rafael",
    content: "Dra. Paula gostou da ideia do agendamento online, mas precisa alinhar com a sócia antes de avançar. Retomar na quinta.",
    created_at: iso(2, 16, 45),
  },
  {
    id: "note_02",
    lead_id: "lead_oliveira_motors",
    author_id: "usr_rafael",
    content: "Ricardo respondeu rápido e pediu detalhes. Preparar exemplos de vitrines de outras lojas antes de responder.",
    created_at: iso(1, 15, 40),
  },
  {
    id: "note_03",
    lead_id: "lead_urbana_moda",
    author_id: "usr_zack",
    content: "Bianca pediu desconto de 15%. Avaliar fechar com 10% + parcelamento em 3x.",
    created_at: iso(3, 18, 0),
  },
];

const TASKS: Task[] = [
  {
    id: "task_01",
    organization_id: ORG_ID,
    lead_id: "lead_gomes_freitas",
    assigned_to: "usr_mariana",
    type: "mensagem",
    title: "Enviar primeira abordagem — Gomes & Freitas",
    description: "Usar a abordagem gerada com foco na vitrine de imóveis.",
    due_date: future(0, 11),
    priority: "alta",
    completed: false,
    completed_at: null,
    created_at: iso(2, 9, 0),
  },
  {
    id: "task_02",
    organization_id: ORG_ID,
    lead_id: "lead_horizonte_prime",
    assigned_to: "usr_mariana",
    type: "follow_up",
    title: "Follow-up 1 — Horizonte Prime",
    description: "Sem resposta desde o primeiro contato há 3 dias.",
    due_date: future(-1, 10),
    priority: "alta",
    completed: false,
    completed_at: null,
    created_at: iso(3, 11, 10),
  },
  {
    id: "task_03",
    organization_id: ORG_ID,
    lead_id: "lead_oliveira_motors",
    assigned_to: "usr_rafael",
    type: "mensagem",
    title: "Responder Ricardo (Oliveira Motors)",
    description: "Ele perguntou como funcionaria a vitrine. Enviar explicação curta + 2 exemplos.",
    due_date: future(0, 15),
    priority: "alta",
    completed: false,
    completed_at: null,
    created_at: iso(1, 15, 30),
  },
  {
    id: "task_04",
    organization_id: ORG_ID,
    lead_id: "lead_studio_norte",
    assigned_to: "usr_zack",
    type: "reuniao",
    title: "Reunião — Studio Norte Arquitetura",
    description: "Apresentar proposta de site portfólio. Link da chamada no convite.",
    due_date: future(0, 16),
    priority: "alta",
    completed: false,
    completed_at: null,
    created_at: iso(1, 10, 5),
  },
  {
    id: "task_05",
    organization_id: ORG_ID,
    lead_id: "lead_essenza_estetica",
    assigned_to: "usr_rafael",
    type: "follow_up",
    title: "Cobrar retorno da proposta — Essenza",
    description: "Proposta enviada há 5 dias sem resposta.",
    due_date: future(-2, 11),
    priority: "media",
    completed: false,
    completed_at: null,
    created_at: iso(2, 9, 20),
  },
  {
    id: "task_06",
    organization_id: ORG_ID,
    lead_id: "lead_marina_nutri",
    assigned_to: "usr_mariana",
    type: "follow_up",
    title: "Follow-up 2 — Marina Queirós",
    description: "Disse que não era prioridade agora. Retomar com ângulo de captação de pacientes online.",
    due_date: future(-3, 9),
    priority: "media",
    completed: false,
    completed_at: null,
    created_at: iso(6, 10, 0),
  },
  {
    id: "task_07",
    organization_id: ORG_ID,
    lead_id: "lead_clinica_lumina",
    assigned_to: "usr_rafael",
    type: "follow_up",
    title: "Retomar com Dra. Paula após conversa com sócia",
    description: null,
    due_date: future(1, 14),
    priority: "media",
    completed: false,
    completed_at: null,
    created_at: iso(2, 17, 0),
  },
  {
    id: "task_08",
    organization_id: ORG_ID,
    lead_id: "lead_urbana_moda",
    assigned_to: "usr_zack",
    type: "proposta",
    title: "Enviar contraproposta — Urbana Moda",
    description: "10% de desconto + 3x. Validar valores antes de enviar.",
    due_date: future(2, 10),
    priority: "alta",
    completed: false,
    completed_at: null,
    created_at: iso(3, 18, 10),
  },
  {
    id: "task_09",
    organization_id: ORG_ID,
    lead_id: "lead_hotel_miradouro",
    assigned_to: "usr_zack",
    type: "outra",
    title: "Kickoff do projeto — Hotel Miradouro",
    description: "Agendar reunião de início do projeto do motor de reservas.",
    due_date: iso(5, 10),
    priority: "media",
    completed: true,
    completed_at: iso(5, 11, 30),
    created_at: iso(7, 15, 30),
  },
];

const CONVERSATIONS: Conversation[] = [
  {
    id: "conv_oliveira",
    organization_id: ORG_ID,
    lead_id: "lead_oliveira_motors",
    channel: "whatsapp",
    last_message_at: iso(1, 15, 22),
    unread: true,
  },
  {
    id: "conv_lumina",
    organization_id: ORG_ID,
    lead_id: "lead_clinica_lumina",
    channel: "whatsapp",
    last_message_at: iso(2, 16, 40),
    unread: false,
  },
  {
    id: "conv_marina",
    organization_id: ORG_ID,
    lead_id: "lead_marina_nutri",
    channel: "whatsapp",
    last_message_at: iso(6, 9, 45),
    unread: false,
  },
];

const MESSAGES: Message[] = [
  {
    id: "msg_01",
    conversation_id: "conv_oliveira",
    direction: "out",
    content:
      "Fala Ricardo, tudo certo? Dei uma olhada no Instagram da Oliveira Motors e reparei que vocês publicam o estoque todo dia — mas quem chega pelo perfil precisa rolar o feed ou chamar no WhatsApp pra saber o que tem dentro do que procura. Pensei numa forma de facilitar essa parte sem mudar como vocês já trabalham. Posso te mostrar?",
    classification: null,
    created_at: iso(4, 10, 5),
  },
  {
    id: "msg_02",
    conversation_id: "conv_oliveira",
    direction: "in",
    content: "Opa, tudo certo. Como funcionaria isso?",
    classification: "quer_saber_mais",
    created_at: iso(1, 15, 22),
  },
  {
    id: "msg_03",
    conversation_id: "conv_lumina",
    direction: "out",
    content:
      "Olá Dra. Paula! Obrigado pela reunião de ontem. Como combinado, vou preparar a proposta do site com agendamento online e envio até sexta.",
    classification: null,
    created_at: iso(3, 9, 15),
  },
  {
    id: "msg_04",
    conversation_id: "conv_lumina",
    direction: "in",
    content: "Perfeito! Vou conversar com minha sócia essa semana e te retorno.",
    classification: "pediu_retorno_futuro",
    created_at: iso(2, 16, 40),
  },
  {
    id: "msg_05",
    conversation_id: "conv_marina",
    direction: "out",
    content:
      "Oi Marina, tudo bem? Vi seu perfil e percebi que suas consultas online são divulgadas só pelos stories — quem quer marcar precisa te chamar no direct e esperar resposta. Pensei numa forma de simplificar isso pra você. Posso te contar?",
    classification: null,
    created_at: iso(9, 14, 0),
  },
  {
    id: "msg_06",
    conversation_id: "conv_marina",
    direction: "in",
    content: "Oi! Achei interessante, mas agora não é prioridade pra mim. Pode me chamar mais pra frente?",
    classification: "sem_prioridade",
    created_at: iso(6, 9, 45),
  },
];

const PROPOSALS: Proposal[] = [
  {
    id: "prop_essenza",
    organization_id: ORG_ID,
    lead_id: "lead_essenza_estetica",
    service: "Landing page de procedimentos + agendamento online",
    value: 2900,
    discount: 0,
    valid_until: future(10),
    notes: "Inclui 3 meses de suporte e ajustes.",
    status: "enviada",
    created_at: iso(5, 14, 15),
    updated_at: iso(5, 14, 15),
  },
  {
    id: "prop_urbana",
    organization_id: ORG_ID,
    lead_id: "lead_urbana_moda",
    service: "Catálogo online integrado ao WhatsApp",
    value: 4100,
    discount: 10,
    valid_until: future(7),
    notes: "Contraproposta: 10% de desconto + parcelamento em 3x.",
    status: "visualizada",
    created_at: iso(6, 11, 0),
    updated_at: iso(3, 17, 35),
  },
  {
    id: "prop_miradouro",
    organization_id: ORG_ID,
    lead_id: "lead_hotel_miradouro",
    service: "Site institucional + motor de reservas diretas",
    value: 5900,
    discount: 0,
    valid_until: iso(10),
    notes: null,
    status: "aceita",
    created_at: iso(14, 10, 0),
    updated_at: iso(7, 15, 0),
  },
];

export function buildSeedDatabase(): Database {
  return {
    organization: {
      id: ORG_ID,
      name: "Atlas Digital",
      logo_url: null,
      currency: "BRL",
      timezone: "America/Sao_Paulo",
      country: "Brasil",
      created_at: iso(90),
    },
    users: USERS,
    company_profile: {
      organization_id: ORG_ID,
      company_name: "Atlas Digital",
      what_we_sell:
        "Sites profissionais, landing pages, catálogos online e sistemas web sob medida para pequenos e médios negócios.",
      target_customers:
        "Negócios locais com boa presença no Instagram mas sem estrutura digital própria: imobiliárias, lojas de veículos, clínicas, estéticas e comércio.",
      main_services: [
        "Site institucional",
        "Site imobiliário com filtros",
        "Vitrine digital de estoque",
        "Landing page com agendamento",
        "Catálogo online integrado ao WhatsApp",
      ],
      average_ticket: "R$ 3.000 – R$ 7.000",
      differentiators: [
        "Entrega em até 21 dias",
        "Integração com o WhatsApp que o cliente já usa",
        "Suporte incluso nos 3 primeiros meses",
      ],
      problems_we_solve: [
        "Dependência total do atendimento manual no WhatsApp",
        "Estoque/portfólio sem vitrine própria navegável",
        "Perda de clientes que pesquisam fora do horário comercial",
      ],
      priority_niches: ["Imobiliária", "Loja de veículos", "Clínica", "Estética", "Loja de roupas"],
      communication_style:
        "Humano, direto e consultivo. Sem jargão técnico. Curiosidade antes de explicar a solução.",
      never_say: [
        "Prometer resultados financeiros específicos",
        "Criticar o trabalho atual do prospect",
        "Mencionar concorrentes pelo nome",
      ],
    },
    leads: LEADS,
    lead_analysis: ANALYSES,
    lead_score_history: SCORE_HISTORY,
    pipeline_stages: STAGES,
    activities: ACTIVITIES,
    notes: NOTES,
    tasks: TASKS,
    campaigns: CAMPAIGNS,
    ai_generations: [],
    conversations: CONVERSATIONS,
    messages: MESSAGES,
    proposals: PROPOSALS,
    automation_rules: [
      {
        id: "auto_01",
        organization_id: ORG_ID,
        name: "Priorizar leads quentes",
        trigger: "Lead recebe score",
        condition: "Score ≥ 80",
        actions: ["Mover para Qualificado", "Criar tarefa de contato"],
        active: true,
        runs: 23,
        created_at: iso(40),
      },
      {
        id: "auto_02",
        organization_id: ORG_ID,
        name: "Pausar cadência ao responder",
        trigger: "Lead respondeu",
        condition: "Sempre",
        actions: ["Pausar follow-ups automáticos", "Criar tarefa para o responsável"],
        active: true,
        runs: 11,
        created_at: iso(40),
      },
      {
        id: "auto_03",
        organization_id: ORG_ID,
        name: "Proposta após reunião",
        trigger: "Reunião concluída",
        condition: "Sempre",
        actions: ["Criar tarefa \"Enviar proposta\""],
        active: false,
        runs: 4,
        created_at: iso(30),
      },
    ],
    notifications: [
      {
        id: "ntf_01",
        organization_id: ORG_ID,
        user_id: "usr_zack",
        title: "Oliveira Motors respondeu",
        body: "\"Como funcionaria isso?\" — classificado como Quer saber mais.",
        link: "/leads/lead_oliveira_motors",
        read: false,
        created_at: iso(1, 15, 23),
      },
      {
        id: "ntf_02",
        organization_id: ORG_ID,
        user_id: "usr_zack",
        title: "3 follow-ups estão vencidos",
        body: "Horizonte Prime, Essenza Estética e Marina Queirós aguardam retomada.",
        link: "/follow-ups",
        read: false,
        created_at: iso(0, 8, 0),
      },
      {
        id: "ntf_03",
        organization_id: ORG_ID,
        user_id: "usr_zack",
        title: "Novo lead recebeu score 95",
        body: "Gomes & Freitas Imóveis está pronto para abordagem.",
        link: "/leads/lead_gomes_freitas",
        read: true,
        created_at: iso(5, 16, 21),
      },
      {
        id: "ntf_04",
        organization_id: ORG_ID,
        user_id: "usr_zack",
        title: "Proposta há 5 dias sem resposta",
        body: "Essenza Estética visualizou mas não respondeu a proposta de R$ 2.900.",
        link: "/propostas",
        read: false,
        created_at: iso(0, 7, 30),
      },
    ],
    audit_logs: [],
    integrations: [
      { id: "int_openai", organization_id: ORG_ID, provider: "OpenAI", status: "desconectada", last_sync_at: null },
      { id: "int_google", organization_id: ORG_ID, provider: "Google Places", status: "desconectada", last_sync_at: null },
      { id: "int_whatsapp", organization_id: ORG_ID, provider: "WhatsApp Business", status: "desconectada", last_sync_at: null },
      { id: "int_gmail", organization_id: ORG_ID, provider: "Gmail", status: "desconectada", last_sync_at: null },
      { id: "int_calendar", organization_id: ORG_ID, provider: "Google Calendar", status: "desconectada", last_sync_at: null },
      { id: "int_n8n", organization_id: ORG_ID, provider: "n8n", status: "desconectada", last_sync_at: null },
      { id: "int_supabase", organization_id: ORG_ID, provider: "Supabase", status: "desconectada", last_sync_at: null },
    ],
    webhooks: [],
    prospecting_jobs: [],
    settings: {
      default_niche: "imobiliaria",
      default_country: "Brasil",
      min_score: 60,
      message_tone: "consultivo",
      message_language: "pt-BR",
    },
    onboarding_completed: true,
  };
}
